Accomodate for HiveConf overwriting defaults in copy constructor
linkedin/iceberg pull request #79
Opened 2021-07-16 04:50 UTC by SurenNihalani

2021-07-17 01:00 UTC, funcheetah commented
Could you please add description and tests done? Thanks.

2021-07-18 03:17 UTC, SurenNihalani commented
Copy pasted them from the commit and added internal jira

2021-07-19 16:52 UTC, shenodaguirguis requested changes
how about adding a test that reproduces the issue of BDP-7063?
Also, there are failing checks (java 11 failed, and java 8 cancelled)

2021-07-19 16:52 UTC, shenodaguirguis commented on hive-metastore/src/main/java/org/apache/iceberg/hive/HiveClientPool.java
>      this.hiveConf = new HiveConf(conf, HiveClientPool.class);
looks like user can control the behavior of loading defaults from the `conf.loadDefaults` itself: https://hadoop.apache.org/docs/r2.6.4/api/org/apache/hadoop/conf/Configuration.html#Configuration()

also, the javadoc Configuration.java states that some configurations are defined as final and cannot be altered:

> Configuration parameters may be declared final. Once a resource declares a value final, no subsequently-loaded resource can alter that value. For example, one might define a final parameter with: 
>     <property>
>       <name>dfs.hosts.include</name>
>       <value>/etc/hadoop/conf/hosts.include</value>
>       <final>true</final>
>     </property>
> Administrators typically define parameters as final in core-site.xml for values that user applications may not alter.
> > 

so if user is trying to overwrite a final property, it should not work even with line 52 added

2021-07-21 02:55 UTC, SurenNihalani commented on hive-metastore/src/main/java/org/apache/iceberg/hive/HiveClientPool.java
>      this.hiveConf = new HiveConf(conf, HiveClientPool.class);
This is not about the behavior of Configuration. It's about the behavior of HiveConf

2021-08-24 04:55 UTC, SurenNihalani commented
@shenodaguirguis  , I am unable to figure out what the code path that leads to this because intellij won't show the path while debugging (I don't know if it knows it or not). So, I can't write tests to reproduce it. I know it fixes the issue but I don't have tests to fix it

2021-08-31 01:15 UTC, shenodaguirguis approved these changes
discussed offline with @SurenNihalani , there is no clear path to test these changes via unit test, but Suren did test the jar with the affected flow and it does solve the issue. Also Suren will rebase and retest to see if failing tests pass.

2021-08-31 02:15 UTC, SurenNihalani commented
~/IdeaProjects/iceberg suren   snihalan-mn2.linkedin.biz
./gradlew check -Pquick=true -x javadoc                                                                                                      -130-
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :iceberg-common:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :iceberg-api:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-api:compileTestJava
Note: /Users/snihalan/IdeaProjects/iceberg/api/src/test/java/org/apache/iceberg/TestMetricsSerialization.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-nessie:compileJava
warning: unknown enum constant SchemaType.OBJECT
  reason: class file for org.eclipse.microprofile.openapi.annotations.enums.SchemaType not found
warning: unknown enum constant SchemaType.OBJECT
warning: unknown enum constant SchemaType.OBJECT
warning: unknown enum constant SchemaType.OBJECT
Note: /Users/snihalan/IdeaProjects/iceberg/nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 warnings

> Task :iceberg-orc:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :iceberg-aws:compileJava
Note: /Users/snihalan/IdeaProjects/iceberg/aws/src/main/java/org/apache/iceberg/aws/glue/DynamoLockManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-hive-metastore:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/snihalan/IdeaProjects/iceberg/hive-metastore/src/main/java/org/apache/iceberg/hive/legacy/LegacyHiveTableOperations.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-nessie:compileTestJava
warning: unknown enum constant SchemaType.OBJECT
  reason: class file for org.eclipse.microprofile.openapi.annotations.enums.SchemaType not found
warning: unknown enum constant SchemaType.OBJECT
2 warnings

> Task :iceberg-parquet:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-arrow:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/snihalan/IdeaProjects/iceberg/arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-pig:compileJava
Note: /Users/snihalan/IdeaProjects/iceberg/pig/src/main/java/org/apache/iceberg/pig/PigParquetReader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :iceberg-hive-metastore:compileTestJava
Note: /Users/snihalan/IdeaProjects/iceberg/hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-nessie:quarkus-start
Using Java versions older than 11 to build Quarkus applications is deprecated and will be disallowed in a future release!

> Task :iceberg-mr:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-core:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-flink:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
This application uses the MP Metrics API. The micrometer extension currently provides a compatibility layer that supports the MP Metrics API, but metric names and recorded values will be different. Note that the MP Metrics compatibility layer will move to a different extension in the future.
Failed to index byte: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader

> Task :iceberg-spark:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-spark2:compileJava
Note: /Users/snihalan/IdeaProjects/iceberg/spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :iceberg-spark3:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :iceberg-spark3-extensions:compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
there was one feature warning; re-run with -feature for details
one warning found

> Task :iceberg-data:compileTestJava
Note: /Users/snihalan/IdeaProjects/iceberg/data/src/test/java/org/apache/iceberg/TestMergingMetrics.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-mr:compileTestJava
Note: /Users/snihalan/IdeaProjects/iceberg/mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-hive3:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/snihalan/IdeaProjects/iceberg/mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-flink:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-spark:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-spark3:compileTestJava
Note: /Users/snihalan/IdeaProjects/iceberg/spark3/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction3.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :iceberg-spark2:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/snihalan/IdeaProjects/iceberg/spark2/src/test/java/org/apache/iceberg/examples/SnapshotFunctionalityTe [...]

2021-08-31 02:15 UTC, merged